fix publish

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -22,7 +22,7 @@ jobs:
         run: |
           set -eu
           if ! [[ "$VERSION" =~ ^v([0-9]+)\.([0-9]+)$ ]]; then 
-            echo "invalid version name" >&2
+            echo "invalid version name: $VERSION" >&2
             exit -1
           fi
 
